# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JustGo-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxAlamofire'
  pod 'Alamofire'
  pod 'RxCocoa'

  # Pods for JustGo-iOS

  target 'JustGo-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JustGo-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
